dbt_project:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      user: "{{ env_var('DB_USER', 'postgres') }}"
      pass: "{{ env_var('DB_PASSWORD', 'postgres') }}"
      dbname: "{{ env_var('DB_NAME', 'real_estate_db') }}"
      schema: gold
      search_path: "gold, public"
  target: dev
